sudo: false

services:
  - mongodb

addons:
  apt:
    packages:
      - oracle-java8-installer

before_cache:
  - find . -name "*.py[co]" -print -delete
  - rm -fv $HOME/.ivy2/pants/*.{css,properties,xml,xsl}
  - rm -rf $HOME/.cache/pants/stats

cache:
  directories:
    - $HOME/.cache/pants
    - $HOME/.ivy2/pants
    - $HOME/.ivy2/pants

language: python

python:
  - "2.7"

env:
  global:
    - JAVA_HOME="/usr/lib/jvm/java-8-oracle"
    - PANTS_CONFIG_OVERRIDE="['pants.ini', 'pants-travis-ci.ini']"

before_script: |
  ls -ls /usr/lib/jvm
  /usr/lib/jvm/java-8-oracle/bin/java -version
  mkdir ~/opt
  cd ~/opt
  wget --no-cookies --no-check-certificate --header \
  "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
  "http://download.oracle.com/otn-pub/java/jdk/8u40-b25/jdk-8u40-linux-x64.tar.gz"
  tar xzf jdk-8u40-linux-x64.tar.gz
  cd -
script: |
  uname -a
  export JAVA_HOME=~/opt/jdk1.8.0_40/
  ./pants -ldebug test test/jvm/io/fsq/spindle::
