sudo: false

services:
  - mongodb

addons:
  apt:
    packages:
      - oracle-java8-installer

before_cache:
  - find . -name "*.py[co]" -print -delete
  - rm -fv $HOME/.ivy2/pants/*.{css,properties,xml,xsl}
  - rm -rf $HOME/.cache/pants/stats

cache:
  directories:
    # These three are Fsq.io specific and hold artifacts that were intended to be managed by a shared artifact cache.
    - .local_artifact_cache/fsqio_pants_pom_pom_resolve_PomResolve
    - $HOME/.pom2
    # # The fsqio and pants virtualenvs and shaded tooling.
    - $HOME/.cache/fsqio
    - $HOME/.cache/pants
    - $HOME/.ivy2/pants
    # # The install location for our managed JDK install.
    - $HOME/opt

language: python

python:
  - "2.7"

env:
  global:
    - JAVA_HOME="$HOME/opt/jdk1.8.0_40"
    - PANTS_CONFIG_OVERRIDE="['pants.ini', 'pants-travis-ci.ini']"

before_script: |
  if ! "$HOME"/opt/jdk1.8.0_40/bin/java -version; then
    mkdir -p ~/opt && cd ~/opt
    wget --no-cookies --no-check-certificate --header \
      "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
      "http://download.oracle.com/otn-pub/java/jdk/8u40-b25/jdk-8u40-linux-x64.tar.gz"
    tar xzf jdk-8u40-linux-x64.tar.gz
    cd -
  fi
script: |
  uname -a
  ./pants test test::
