sudo: false

services:
  - mongodb

before_cache:
  - find . -name "*.py[co]" -print -delete
  - rm -fv $HOME/.ivy2/pants/*.{css,properties,xml,xsl}
  # The stats cache contains timestamped reports unused by CI but that
  # thrash the cache.  Skip caching these.
  - rm -rf $HOME/.cache/pants/stats

cache:
  directories:
    - $HOME/.cache/pants
    - $HOME/.ivy2/pants
    - $HOME/.ivy2/pants

language: python

python:
  - "2.7"

env:
  global:
    - PANTS_CONFIG_OVERRIDE="['pants.ini', 'pants-travis-ci.ini']"

before_script: |
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

script: |
  uname -a
  java -version
  ./pants buildgen
  ./pants compile src::
  ./pants test test::
