sudo: false

services:
  - mongodb

before_cache:
  - find . -name "*.py[co]" -print -delete
  - rm -fv $HOME/.ivy2/pants/*.{css,properties,xml,xsl}
  - rm -rf $HOME/.cache/pants/stats

cache:
  directories:
    - $HOME/.cache/pants
    - $HOME/.ivy2/pants
    - $HOME/.ivy2/pants

language: python

python:
  - "2.7"

env:
  global:
    - JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
    - PANTS_CONFIG_OVERRIDE="['pants.ini', 'pants-travis-ci.ini']"

before_script:
  ls -ls /usr/lib/jvm
script: |
  uname -a
  ./pants test test/jvm/io/fsq/spindle::
