#!/bin/bash

set -e

if [[ -z "$SKIP_UPKEEP" ]]; then
  ./upkeep
fi

if [ "$(uname)" == "Darwin" ]; then
  export JDK_HOME=$(/usr/libexec/java_home -v 1.8.0_40)
else
  if [ ! -f /data/loko/infrastructure-jdk8/current/bin/java ]; then
    echo "Pants must have the infrastructure-jdk8 loko package installed in order"
    echo " to run on linux."
    exit 1
  fi
  export JAVA_HOME="/data/loko/infrastructure-jdk8/current"
fi

if [ -z "$PANTSBINARY" ]; then
  exec .pantsenv/bin/pants --print-exception-stacktrace "$@"
else
  export PYTHONPATH=src/python
  exec $PANTSBINARY --print-exception-stacktrace "$@"
fi
