# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'spindle',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:fscommon-thrift-bson',
    '3rdparty:mongodb',
    '3rdparty:rogue-field',
    '3rdparty:spindle-runtime',
    '3rdparty:thrift',
    'src/jvm/io/fsq/rogue',
    'src/jvm/io/fsq/rogue/index',
  ],
  tags = [
    'fscommon',
  ],
)
