# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

scala_library(
  name = 'runtime',
  sources = globs('*.scala'),
  tags = ['fscommon'],
  dependencies = [
    '3rdparty:joda-time',
    '3rdparty:rogue-field',
    '3rdparty:thrift',
    'src/jvm/io/fsq/common/thrift/bson',
    'src/jvm/io/fsq/common/thrift/json',
  ],
)
