# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

spindle_thrift_library(
  name = 'talent',
  dependencies = [
    'test/thrift/io/fsq/thriftexample/people',
  ],
  sources = globs('*.thrift'),
)
