# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

spindle_thrift_library(
  name = 'av',
  dependencies = [
    'test/thrift/io/fsq/thriftexample/talent',
  ],
  sources = globs('*.thrift'),
)
