# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

junit_tests(
  name = 'test',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:fscommon-thrift-base',
    '3rdparty:fscommon-thrift-bson',
    '3rdparty:fscommon-thrift-json',
    '3rdparty:jackson',
    '3rdparty:junit',
    '3rdparty:mongodb',
    '3rdparty:phonenumbers',
    '3rdparty:specs',
    '3rdparty:spindle-runtime',
    '3rdparty:thrift',
    'test/thrift/io/fsq/spindle/codegen/test',
    'test/thrift/io/fsq/spindle/thriftexample',
    'test/thrift/io/fsq/spindle/thriftexample/av',
    'test/thrift/io/fsq/spindle/thriftexample/people',
    'test/thrift/io/fsq/spindle/thriftexample/talent',
  ],
)
