# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

junit_tests(
  name = 'test',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:joda-time',
    '3rdparty:junit',
    '3rdparty:mongodb',
    '3rdparty:rogue-field',
    '3rdparty:specs2',
    '3rdparty:spindle-runtime',
    'src/jvm/io/fsq/rogue',
    'src/jvm/io/fsq/rogue/indexchecker',
    'src/jvm/io/fsq/rogue/spindle',
    'test/thrift/io/fsq/rogue/spindle/test',
  ],
)
